# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    NF_BEFORE_SCRIPT: |
        mkdir demo_data && wget -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/clair-tutorial/demo_data.tar.gz && tar -xzvf  demo_data.tar.gz
    NF_WORKFLOW_OPTS: "--bam demo_data/HG003_chr20_demo.bam --bed demo_data/quick_demo.bed --ref demo_data/GRCh38_no_alt_chr20.fa"

